### ISSUE TITLE
Comments on the eRum blog post

### ISSUE THREAD

**Issue by csgillespie** [jumpingrivers-blog/jumpingrivers-blog.github.io#8]
@daroczig The draft blog post is available at

https://github.com/jumpingrivers-blog/jumpingrivers-blog.github.io/blob/master/content/posts/drafts/2018-XX-XX-eRum.Rmd

Suggestions & PRs welcome

**Comment by daroczig** [comment]
Thanks, looks good :+1: 

One suggestion, though: the registration deadline for the conference is April 29, 2018 -- can we please have a deadline here that's before that? So that we/you guys would still have time to evaluate the submissions, decide on the best one and share a 100% discount code with the winner. Eg April 15?

**Comment by daroczig** [comment]
Oh, never mind, I somehow read May 2 instead of April 2 -- all good! Maybe add timezone info for the 5pm :)
